id = "twig"
name = "Twig"
version = "0.2.0"
schema_version = 1
authors = ["Yussuf Sassi <yussuf@tuta.io>"]
description = "Syntax highlighting and Intellisense for Twig in Zed"
repository = "https://github.com/YussufSassi/zed-twig"

[grammars.twig]
repository = "https://github.com/jannisborgers/tree-sitter-twig"
commit = "723926cff978453c40ee11ca8046de0cb248873c"

[language_servers.twiggy-language-server]
name = "Twiggy Language Server"
language = "Twig"
